// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Attach() {
  return window['go']['desktop']['App']['Attach']();
}

export function BuildInfo() {
  return window['go']['desktop']['App']['BuildInfo']();
}

export function CurrentStatus() {
  return window['go']['desktop']['App']['CurrentStatus']();
}

export function DetachAll() {
  return window['go']['desktop']['App']['DetachAll']();
}

export function DisableFeature(arg1) {
  return window['go']['desktop']['App']['DisableFeature'](arg1);
}

export function EnableFeature(arg1) {
  return window['go']['desktop']['App']['EnableFeature'](arg1);
}

export function Features() {
  return window['go']['desktop']['App']['Features']();
}

export function GetSavedMods() {
  return window['go']['desktop']['App']['GetSavedMods']();
}

export function ListTables() {
  return window['go']['desktop']['App']['ListTables']();
}

export function LoadTable(arg1) {
  return window['go']['desktop']['App']['LoadTable'](arg1);
}

export function ReloadTable() {
  return window['go']['desktop']['App']['ReloadTable']();
}

export function SetFeatureValue(arg1, arg2) {
  return window['go']['desktop']['App']['SetFeatureValue'](arg1, arg2);
}

export function SetSaveModsEnabled(arg1) {
  return window['go']['desktop']['App']['SetSaveModsEnabled'](arg1);
}

export function SyncTables() {
  return window['go']['desktop']['App']['SyncTables']();
}

export function TableSource(arg1) {
  return window['go']['desktop']['App']['TableSource'](arg1);
}
