// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {desktop} from '../models';

export function Attach():Promise<desktop.AttachResult>;

export function BuildInfo():Promise<desktop.BuildInfo>;

export function CurrentStatus():Promise<desktop.AppStatus>;

export function DetachAll():Promise<void>;

export function DisableFeature(arg1:string):Promise<void>;

export function EnableFeature(arg1:string):Promise<void>;

export function Features():Promise<Array<desktop.FeatureView>>;

export function GetSavedMods():Promise<desktop.SavedMods>;

export function ListTables():Promise<Array<desktop.TableSummary>>;

export function LoadTable(arg1:string):Promise<Array<desktop.FeatureView>>;

export function ReloadTable():Promise<desktop.ReloadResult>;

export function SetFeatureValue(arg1:string,arg2:number):Promise<void>;

export function SetSaveModsEnabled(arg1:boolean):Promise<void>;

export function SyncTables():Promise<desktop.TableSyncResult>;

export function TableSource(arg1:string):Promise<string>;
